### ISSUE TITLE
Linux building

### ISSUE THREAD

**Issue by mrzzzrm** [hpicgs/globjects#263]
I have a few problems building globjects-test and the glfw examples on Linux, some 13.10 32 bit ubuntu :(  (I am going to update... soonish!). I think this is general Linux/Unix stuff however. I have local hacks to work around them, however no time for proper fixing atm, so I'll just leave them here.

* GMock (and GTest I think) depend on pthread. The corresponding flag is listed in PlatformLinuxGCC.cmake but doesn't seem to reach the g++ invokation for globjects-test.
* GLFW has some dependencies (`-lGL -lXxf86vm -lX11 -lXrandr -lXi` here) that aren't currently being linked.
* glm uses anonymous structs, something -pedantic doesn't like (https://github.com/g-truc/glm/issues/2519). glm probably isn't going to fix this soon, but there seems to be the possibility to disable swizzling via a define, thus keeping the -pedantic from firing. (Interestingly I raised this already some time ago for glow and considered it fixed after a while. It clearly isn't, though... Dunno what happened there)

**Comment by scheibel** [comment]
So far, enabling ```-pedantic``` doesn't result in any additional warnings or errors (using glm 0.9.5 and 0.9.6).

**Comment by scheibel** [comment]
I tried using GLFW statically under Ubuntu and it just don't work as GLFW don't support our way of linking third parties and providing the additionally needed dependencies (even with adding the aforementioned additional dependencies by myself it won't link).
However, dynamic linking works like a charm.

**Comment by scheibel** [comment]
The linking error with gmock and gtest can't be reproduced (maybe accidentally fixed)?
