### ISSUE TITLE
Remove ref_ptr

### ISSUE THREAD

**Issue by scheibel** [hpicgs/globjects#276]
With https://github.com/hpicgs/globjects/pull/275 the discussion comes up why we provide an own implementation of a smart pointer (```ref_ptr```), if the STL provides ```unique_ptr```, ```shared_ptr``` and ```weak_ptr```.

Typically, objects in globjects are strictly related to an OpenGL object, so there is a 1 to 1 correspondence and with a creation or destruction of a globjects objects there should follow the same for the OpenGL object.
As objects (e.g., a shader) can be used in different ways by multiple other objects (e.g., multiple programs sharing the same fragment shader), it may not be clear when an globjects object isn't used anymore and the corresponding OpenGL resource can be freed.
The problem gets even more complicated when we want to allow other OpenGL libraries to use OpenGL objects allocated by globjects (and the other way around).
Therefore, our first solution was to introduce a shared ownership architecture, as it can be established using ```shared_ptr``` or ```ref_ptr```.
```ref_ptr``` has the main advantage over ```shared_ptr``` that the reference counting is on the object itself, resulting in smaller and clearer function signatures.
The disadvantage is the required own implementation, as a ```ref_ptr``` is not shipped with the STL (by now?).

While analyzing past and current rendering systems (e.g., research prototypes, game engines, cg demos) it becomes apparent that there is not only a common phase for creating OpenGL objects but also a dedicated phase were OpenGL objects are freed.
As I assume that every programmer using OpenGL knows (or at least should know) when to allocate and free OpenGL memory, it feels prematurely optimized that we introduced a shared memory ownership and management in the first place.

I suggest we switch back to simple, straight-forward memory management using ```unique_ptr``` (indicating memory ownership) and plain pointers (indicating no memory ownership), as seen in http://stackoverflow.com/questions/8338570/c11-replace-all-non-owning-raw-pointers-with-stdshared-ptr#answer-8376611.

**Comment by mjendruk** [comment]
I am also for option (2) since as @j-o and I already said option (1) would be way less convenient. The `shared_ptr` still allows enough flexibility through deleters and allocators.

Some thoughts on having raw and smart pointers: Supporting smart and raw pointers by abstraction doesn't sound like a good idea to me, because it implies a virtual function call each time a wrapped object is accessed. I had concerns about the use of `shared_ptr`s because of performance reasons, such  wrapper however would be even worse.

**Comment by mrzzzrm** [comment]
What's the status of this?

**Comment by scheibel** [comment]
We don't have finally decided this by now, but we strive for removing ```ref_ptr```, working out a concept of when a user has to manage pointer ownership by himself (e.g., creating a program normally means you have to store the pointer and you have to release it) and for what cases we have to decide on established smart pointers or raw pointers for internal memory management (e.g., for the ```AbstractStringResource``` instances that are normally not created or held by the user).

**Comment by marton78** [comment]
Hi guys,

I just stumbled upon your library and am considering using it in my own projects to replace similar code I've written myself. While I generally like your work, the first things that made me suspicious is

1. The use of naked pointers and `new` in your examples
2. The existence of `ref_ptr`

I strongly suggest you remove `ref_ptr` as well as the embedded reference count from the library. Memory management is an entirely orthogonal to graphics and thus out of scope of  a GL wrapper library. Therefore, I suggest that GLobjects be agnostic of memory management.

A sane design would be that of the move-only types in the STL, e.g. `std::thread`. That is, a class should be

1. non-copyable
2. move-constructible and move-assignable
3. have an empty state in which destruction is a no-op

This way, questions of ownership can be decided by the user:

1. Unique ownership: Allocate object on stack, pass around references (not pointers!) to it and maybe move it 
2. Shared ownership: keep `shared_ptr`s constructed by `make_shared` thereby embedding the reference count into the object.

BTW, in my projects I have never encountered a true use case for shared ownership, to me the use of it indicates bad design, but that should be the concern of your users, not yourselves.

Hope that helps somehow,
keep up the good work,
Marton

**Comment by scheibel** [comment]
My current findings are that we should clearly separate between objects that can be created by the user and the ones that shouldn't be created by the user.
Giving this separation we can ensure that we have full memory ownership and delete responsibility over objects that cannot be created by the user and that we can ignore the delete responsibility for each object that has to be created by the user.

For example, the separation can look like this:

Create by user:
 * AbstractStringSource and subclasses
 * AbstractState
 * AbstractUniform and subclasses
 * Object and subclasses
 * NamedString

Create by library:
 * AbstractFunctionCall
 * AbstractLogHandler
 * FramebufferAttachment and subclasses
 * Capability
 * StateSetting
 * VertexAttributeBinding

This separation would require to remove all convenience interfaces that allow to omit the direct instatiation of objects from the first group (e.g., passing a ```std::string``` to the constructor of Shader, internally creating a ```StaticStringSource``` object).

Further, we can provide additional (user-instantiated) classes in depending libraries that can wrap user-instantiated objects with the responsibility to delete them.

This solution would implement the scenario of a memory-management agnostic OpenGL wrapper from @marton78 (thanks for your insights).

**Comment by scheibel** [comment]
I close this for now as we have to decide internally on how to proceed with this issue.
