### ISSUE TITLE
Logging doesn't support glbinding's types

### ISSUE THREAD

**Issue by mrzzzrm** [hpicgs/globjects#277]
One can write e.g. ```gl::GLenum```s to a ```std::ostream``` thanks to the overloads in ```gl/types.h```. ```globjects::LogMessageBuilder``` however can't output them, even though globjects and glbinding are pretty tightly coupled.

**Comment by scheibel** [comment]
I added more types to the logging but are there any other missing?
```GLbitfield``` is a special case since it is currently just a typedef to an unsigned int...I don't know whether we are fixing this so it can be printed using ```0```s and ```1```s.
