### ISSUE TITLE
Support OpenGL ES

### ISSUE THREAD

**Issue by cgcostume** [hpicgs/globjects#37]
some articles:
http://www.altdevblogaday.com/2013/08/18/the-main-loop-in-devils-attorney-on-android/

**Comment by scheibel** [comment]
I think we need to start this issue over again if we want OpenGL ES support someday. Close for now.

**Comment by headupinclouds** [comment]
Has there been any further progress or discussions regarding OpenGL ES support in your projects (glbinding, etc)?

**Comment by scheibel** [comment]
Thanks for showing interest. This feature is currently on our roadmap but not in active development.
Once it is in active development, we expect results within two weeks.
